package Usoarchivos.serializacion;

import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Usoarchivos.serializacion.AccesoArchivo;
import Usoarchivos.serializacion.Alumno;
import Usoarchivos.serializacion.Carrera;
import Usoarchivos.serializacion.FrmListaAlumnos;
import Usoarchivos.serializacion.FrmRegistroAlumno;

public class FrmCalificaciones extends javax.swing.JFrame {

    private String numControl;
    private String nombre;
    private String apellido;
    private String carrera;

    public FrmCalificaciones() {
        this("Alumno de prueba", "Carrera de prueba","", "NumControl");
         
    }

    public FrmCalificaciones(String numControl, String nombre, String apellido, String carrera) {
        initComponents();
        this.numControl = numControl;
        this.nombre = nombre;
        this.apellido = apellido;
        this.carrera = carrera;

        String fullName = nombre + " " + apellido;

        lblNombre.setText(fullName);
        lblCarrera.setText(carrera);
        lblNumControl.setText(numControl);

        cargarTabla();
    }

    private void cargarTabla(){
        ArrayList calificaciones=AccesoArchivo.leerArchivo("calificaciones.txt");
        cargarTabla(calificaciones);
    }
   private void cargarTabla(ArrayList calificaciones) {
    if (calificaciones != null) {
        DefaultTableModel contenidoTabla = (DefaultTableModel) tblCalificaciones.getModel();
        contenidoTabla.setRowCount(0);
        for (Object calificacion : calificaciones) {
            Calificacion a = (Calificacion) calificacion;
            
            // Verifica si el número de control del alumno no es nulo antes de comparar
            if (a.getNumControl() != null && a.getNumControl().getNoControl().equals(this.numControl)) {
                contenidoTabla.addRow(a.toArray());
            }
        }
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnEliminarCalificacion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCalificaciones = new javax.swing.JTable();
        lblCarrera = new javax.swing.JLabel();
        btnCapturarCalificaion = new javax.swing.JButton();
        lblNumControl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombre.setText("Alumno");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnEliminarCalificacion.setText("Eliminar Calificacion");
        btnEliminarCalificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCalificacionActionPerformed(evt);
            }
        });

        tblCalificaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Materia", "Unidad", "Calificacion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCalificaciones);

        lblCarrera.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCarrera.setText("Carrera");

        btnCapturarCalificaion.setText("Capturar Calificacion");
        btnCapturarCalificaion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapturarCalificaionActionPerformed(evt);
            }
        });

        lblNumControl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNumControl.setText("NumControl");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumControl, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 971, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnCapturarCalificaion)
                .addGap(62, 62, 62)
                .addComponent(btnEliminarCalificacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNumControl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarCalificacion)
                    .addComponent(btnSalir))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCapturarCalificaion)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarCalificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCalificacionActionPerformed
        int fila = tblCalificaciones.getSelectedRow();
        if (fila > -1) {
            String materia = tblCalificaciones.getValueAt(fila, 0).toString();
            int unidad = Integer.parseInt(tblCalificaciones.getValueAt(fila, 1).toString());

            int respuesta = JOptionPane.showConfirmDialog(this,
                    "Estás a punto de eliminar la calificación de: " + materia
                    + " de la unidad: " + unidad + ". ¿Deseas continuar?",
                    "Confirmar eliminación",
                    JOptionPane.YES_NO_OPTION);

            if (respuesta == JOptionPane.YES_OPTION) {
                ArchivoCalificaciones.eliminarCalificacion(numControl, materia, unidad);
                JOptionPane.showMessageDialog(this, "Calificación eliminada correctamente.");
                cargarTabla(); 
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecciona la calificación que deseas eliminar.");
        }

    }//GEN-LAST:event_btnEliminarCalificacionActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
        FrmListaAlumnos frmLista = new FrmListaAlumnos();
        frmLista.setVisible(true);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCapturarCalificaionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturarCalificaionActionPerformed
        FrmCapturarCalificacion frm = new FrmCapturarCalificacion(numControl, nombre, apellido, carrera);
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCapturarCalificaionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCalificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCalificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCalificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCalificaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCalificaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapturarCalificaion;
    private javax.swing.JButton btnEliminarCalificacion;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCarrera;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumControl;
    private javax.swing.JTable tblCalificaciones;
    // End of variables declaration//GEN-END:variables
}
