/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Usoarchivos.serializacion;

import Usoarchivos.serializacion.FrmCalificaciones;
import Usoarchivos.serializacion.FrmLogin;
import Usoarchivos.serializacion.FrmMenu;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paveg
 */
public class FrmListaAlumnos extends javax.swing.JFrame {

    /*
     * Creates new form FrmListaAlumnos
     */
    public FrmListaAlumnos() {
        initComponents();
        //Obtener el modelo de la tabla para cambiarlo (con nuevos datos y nuevos renglones)
//        DefaultTableModel contenidoTabla=(DefaultTableModel)tblAlumnos.getModel();
//        Object[] datosAlumno=new Object[5];
//        datosAlumno[0]="S25120001";
//        datosAlumno[1]="Perez";
//        contenidoTabla.addRow(datosAlumno);
        //contenidoTabla.addRow(new Object[]{"S25120001","Perez","Juan",1,"Ing. Sistemas Comp"});
        cargarTabla();
    }
    
    private void cargarTabla(){
        ArrayList alumnos=AccesoArchivo.leerArchivo("inscritos.txt");
        cargarTabla(alumnos);
    }
    private void cargarTabla(ArrayList alumnos){
        if(alumnos!=null){
            DefaultTableModel contenidoTabla=(DefaultTableModel)tblAlumnos.getModel();
            contenidoTabla.setRowCount(0);
            for (Object alumno : alumnos) {
                Alumno a=(Alumno) alumno;
                contenidoTabla.addRow(a.toArray());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlumnos = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnVerCalificaciones = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tblAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num. Control", "Apellidos", "Nombre", "Semestre", "Carrera"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAlumnos);

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEditar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnVerCalificaciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVerCalificaciones.setText("Ver Calificaciones");
        btnVerCalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerCalificacionesActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addGap(40, 40, 40)
                        .addComponent(btnEditar)
                        .addGap(42, 42, 42)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                        .addComponent(btnVerCalificaciones)
                        .addGap(41, 41, 41)
                        .addComponent(btnSalir)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
                        .addGap(22, 22, 22))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnVerCalificaciones)
                    .addComponent(btnSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        FrmRegistroAlumno frm=new FrmRegistroAlumno();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        int fila=tblAlumnos.getSelectedRow();
        if(fila>-1){
            String numControl=tblAlumnos.getValueAt(fila, 0).toString();
            FrmRegistroAlumno frm=new FrmRegistroAlumno(numControl);
            frm.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Selecciona el alumno que deseas editar");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int fila=tblAlumnos.getSelectedRow();
        if(fila>-1){
            String numControl=tblAlumnos.getValueAt(fila, 0).toString();
            String nombre=tblAlumnos.getValueAt(fila, 1).toString() +  " " + 
                    tblAlumnos.getValueAt(fila, 2).toString();
            
            int respuesta=JOptionPane.showConfirmDialog(this, "Estás a punto de eliminar el alumno: " + 
                    nombre +  " con número de control: " + numControl + ". ¿Deseas continuar?",
                    "Confirmar eliminación",
                    JOptionPane.YES_NO_OPTION);
            
            if(respuesta==JOptionPane.YES_OPTION){
                ArrayList<Alumno> alumnos=AccesoArchivo.leerArchivo("inscritos.txt");
                Alumno alumnoABorrar=new Alumno(numControl);
                //Eliminar el alumno que se desea quitar
                alumnos.remove(alumnoABorrar);
                //Se reescribe el archivo sin el alumno que se eliminó
                AccesoArchivo.reescribirArchivo("inscritos.txt", alumnos);
                cargarTabla(alumnos);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Selecciona el alumno que deseas eliminar");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnVerCalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerCalificacionesActionPerformed
        int fila=tblAlumnos.getSelectedRow();
        if(fila>-1){
            String numControl=tblAlumnos.getValueAt(fila, 0).toString();
            String nombre=tblAlumnos.getValueAt(fila, 2).toString();
            String apellido=tblAlumnos.getValueAt(fila, 1).toString();
            String carrera=tblAlumnos.getValueAt(fila, 4).toString();
            FrmCalificaciones frm=new FrmCalificaciones(numControl,nombre,apellido,carrera);
            frm.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Seleccione el alumno que desea ver calificaciones");
        }
    }//GEN-LAST:event_btnVerCalificacionesActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        FrmMenu frm = new FrmMenu();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        FrmMenu frm = new FrmMenu();
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmListaAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmListaAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmListaAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmListaAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmListaAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerCalificaciones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAlumnos;
    // End of variables declaration//GEN-END:variables
}
